export const MOCK_COURSES = [
  {
    id: '1',
    name: 'Machine learning specialization',
    instructorName: 'Andrew Ng',
    description:
      'machine learning machine learning machine learning machine learning machine learning',
    enrolledStudent: 69,
  },
  {
    id: '2',
    name: 'PHASATHAIPHUENTHAN',
    instructorName: 'MAEMUENG',
    description:
      'THTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTHTH',
    enrolledStudent: '420',
  },
  {
    id: '3',
    name: 'Quantum Physics For Baby',
    instructorName: 'Jo Mama',
    description:
      ' bljkdfngpbjnspjgnbs;kglk;bbf ;bs;lknr;nrgnr;jnsg;jbnsgfbnrthnbsglkn;slkntkmbndign;nkentk',
    enrolledStudent: '78910',
  },
];

export const MOCK_ANNOUNCEMENT = [
  {
    id: '1',
    title: 'Tomorrow, we will have a quiz.',
    description: 'Chapter 1-2',
    courseName: 'Zhong gua language',
    readList: ['Ton', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '2',
    title: 'Yesterday, we will have a quiz.',
    description: 'Chapter 6-9',
    courseName: 'Nihonjin language',
    readList: ['TonTOnTONTONTOOTN', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '3',
    title: 'BRUHBRUHBURHBUHURBHURHUBHURU',
    description: 'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    courseName: 'ilove C',
    readList: ['Ton', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '1',
    title: 'Tomorrow, we will have a quiz.',
    description: 'Chapter 1-2',
    courseName: 'Zhong gua language',
    readList: ['Ton', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '2',
    title: 'Yesterday, we will have a quiz.',
    description: 'Chapter 6-9',
    courseName: 'Nihonjin language',
    readList: ['TonTOnTONTONTOOTN', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '3',
    title: 'BRUHBRUHBURHBUHURBHURHUBHURU',
    description: 'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    courseName: 'ilove C',
    readList: ['Ton', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '1',
    title: 'Tomorrow, we will have a quiz.',
    description: 'Chapter 1-2',
    courseName: 'Zhong gua language',
    readList: ['Ton', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '2',
    title: 'Yesterday, we will have a quiz.',
    description: 'Chapter 6-9',
    courseName: 'Nihonjin language',
    readList: ['TonTOnTONTONTOOTN', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '3',
    title: 'BRUHBRUHBURHBUHURBHURHUBHURU',
    description: 'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    courseName: 'ilove C',
    readList: ['Ton', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '1',
    title: 'Tomorrow, we will have a quiz.',
    description: 'Chapter 1-2',
    courseName: 'Zhong gua language',
    readList: ['Ton', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '2',
    title: 'Yesterday, we will have a quiz.',
    description: 'Chapter 6-9',
    courseName: 'Nihonjin language',
    readList: ['TonTOnTONTONTOOTN', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
  {
    id: '3',
    title: 'BRUHBRUHBURHBUHURBHURHUBHURU',
    description: 'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    courseName: 'ilove C',
    readList: ['Ton', 'Nac', 'Jo', 'Jom'],
    createdAt: new Date(),
  },
];
